/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractVersion = "0.1.0";
export type Id = string;
export type Name = string;
export type Id1 = string;
export type ProjectId = string;
export type Label = string;
export type DocumentIds = string[];
export type Id2 = string;
export type Revision = number;
export type Title = string;
export type SourceNote = string;
export type Id3 = string;
export type Title1 = string;
export type Requirement = string;
export type RequiredEvidence = string[];
export type Criteria = Criterion[];
export type Id4 = string;
export type ProjectId1 = string;
export type MaterialVersionId = string;
export type RubricId = string;
export type RubricRevision = number;
export type Mode = "mock" | "live" | "replay";
export type Status = "queued" | "running" | "completed" | "failed";
export type Stage = "pending" | "extract" | "retrieve" | "adjudicate" | "verify" | "aggregate" | "done";
export type Provider = string | null;
export type Model = string | null;
export type PromptVersion = string;
export type Error = string | null;
export type Id5 = string;
export type MaterialVersionId1 = string;
export type LogicalKey = string;
export type Filename = string;
export type Format = "pdf" | "pptx" | "docx" | "md";
export type Sha256 = string;
export type ParseStatus = "pending" | "ready" | "rejected" | "failed";
export type Documents = Document[];
export type Id6 = string;
export type DocumentId = string;
export type Ordinal = number;
export type Text = string;
export type Kind = "page" | "slide" | "paragraph" | "line";
export type Index = number;
export type EndIndex = number | null;
export type BlockIndex = number;
export type Blocks = Block[];
export type Id7 = string;
export type CriterionIds = string[];
export type Text1 = string;
export type BlockId = string;
export type Start = number;
export type End = number;
export type Quote = string;
export type ComparisonKey = string | null;
export type Claims = Claim[];
export type Id8 = string;
export type CriterionId = string;
export type ClaimId = string | null;
export type Relation = "supports" | "contradicts" | "context";
export type CitationValid = boolean;
export type ValidationError = string | null;
export type Evidence = Evidence1[];
export type Id9 = string;
export type Fingerprint = string;
export type CriterionId1 = string;
export type Kind1 =
  "missing_evidence" | "weak_evidence" | "unsupported_claim" | "cross_document_conflict" | "overclaim";
export type Severity = "critical" | "warning" | "info";
export type Title2 = string;
export type Explanation = string;
export type ClaimIds = string[];
export type EvidenceIds = string[];
export type SearchedDocumentIds = string[];
export type Findings = Finding[];
export type Id10 = string;
export type FindingId = string;
export type Instruction = string;
export type Status1 = "todo" | "done";
export type Repairs = Repair[];
export type CriterionId2 = string;
export type Status2 = "supported" | "weak" | "missing" | "critical" | "conflict" | "not_evaluated";
export type EvidenceIds1 = string[];
export type FindingIds = string[];
export type Assessments = CriterionAssessment[];
export type SubmissionReadiness = "not_evaluated" | "blocked" | "needs_review" | "ready";
export type RubricCoverage = number | null;
export type VerifiedEvidence = number;
export type CriticalRisks = number;
export type ResolvedRisks = number | null;
export type Id11 = string;
export type FindingId1 = string;
export type Question = string;
export type Why = string;
export type Outline = string[];
export type EvidenceIds2 = string[];
export type ReviewQuestions = ReviewQuestion[];
export type BeforeRunId = string;
export type AfterRunId = string;
export type Comparable = boolean;
export type Reason = string | null;
export type Fingerprint1 = string;
export type Status3 = "resolved" | "new" | "unchanged";
export type BeforeFindingId = string | null;
export type AfterFindingId = string | null;
export type Entries = DiffEntry[];
export type MaterialVersionId2 = string;
export type RubricId1 = string;
export type RubricRevision1 = number;
export type Mode1 = "live" | "replay";
export type DocumentId1 = string;
export type Filename1 = string;
export type SizeBytes = number;
export type Sha2561 = string;
export type LineCount = number;
export type Blocks1 = Block[];
export type Id12 = string;
export type Filename2 = string;
export type SizeBytes1 = number;
export type Sha2562 = string;
export type LineCount1 = number;
export type CreatedAt = string;
export type Blocks2 = Block[];
export type Id13 = string;
export type Filename3 = string;
export type CreatedAt1 = string;
export type BlockCount = number;
export type Id14 = string;
export type MaterialId = string;
export type BlockId1 = string;
export type Note = string | null;
export type ProposedBy = "human" | "agent";
export type CreatedAt2 = string;
export type BlockId2 = string;
export type Quote1 = string;
export type Note1 = string | null;
export type MaterialId1 = string;
export type RubricId2 = string;
export type RubricRevision2 = number;
export type CreatedAt3 = string;
export type RubricId3 = string;
export type RubricRevision3 = number;
export type Id15 = string;
export type MaterialId2 = string;
export type AnnotationId = string;
export type RubricId4 = string;
export type RubricRevision4 = number;
export type CriterionId3 = string;
export type Rationale = string;
export type ProposedBy1 = "human" | "agent";
export type CreatedAt4 = string;
export type AnnotationId1 = string;
export type CriterionId4 = string;
export type Rationale1 = string;
export type Id16 = string;
export type ProposalId = string;
export type Ordinal1 = number;
export type BlockId3 = string;
export type Quote2 = string;
export type Rationale2 = string;
export type RiskNote = string | null;
export type ValidationStatus = "pending" | "passed" | "invalid";
export type ValidationCode = string | null;
export type ReviewStatus = "unreviewed" | "accepted" | "rejected";
export type RejectReason = string | null;
export type CreatedAnnotationId = string | null;
export type CreatedLinkId = string | null;
export type CreatedAt5 = string;
export type Id17 = string;
export type MaterialId3 = string;
export type CriterionId5 = string;
export type RubricId5 = string;
export type RubricRevision5 = number;
export type Provider1 = string;
export type Model1 = string;
export type PromptVersion1 = string;
export type Status4 = "completed" | "failed";
export type Error1 = string | null;
export type CreatedAt6 = string;
export type Candidates = ProposalCandidate[];
export type CriterionId6 = string;
export type Reason1 = string | null;
export type Code = string;
export type Message = string;
export type Details = string[];

export interface ContractBundle {
  report: RunReport;
  diff: VersionDiff;
  run_request: RunRequest;
  preview: MarkdownPreview;
  saved_material: SavedMaterial;
  material_summary: MaterialSummary;
  evidence_annotation: EvidenceAnnotation;
  evidence_annotation_create: EvidenceAnnotationCreate;
  rubric_binding: RubricBinding;
  rubric_binding_create: RubricBindingCreate;
  criterion_evidence_link: CriterionEvidenceLink;
  criterion_evidence_link_create: CriterionEvidenceLinkCreate;
  proposal_candidate: ProposalCandidate;
  agent_proposal: AgentProposal;
  agent_proposal_create: AgentProposalCreate;
  proposal_candidate_reject: ProposalCandidateReject;
  proposal_acceptance: ProposalAcceptance;
  error: ApiError;
}
export interface RunReport {
  contract_version: ContractVersion;
  project: Project;
  material_version: MaterialVersion;
  rubric: Rubric;
  run: Run;
  documents: Documents;
  blocks: Blocks;
  claims: Claims;
  evidence: Evidence;
  findings: Findings;
  repairs: Repairs;
  assessments: Assessments;
  metrics: Metrics;
  review_questions: ReviewQuestions;
}
export interface Project {
  id: Id;
  name: Name;
}
export interface MaterialVersion {
  id: Id1;
  project_id: ProjectId;
  label: Label;
  document_ids: DocumentIds;
}
export interface Rubric {
  id: Id2;
  revision: Revision;
  title: Title;
  source_note: SourceNote;
  criteria: Criteria;
}
export interface Criterion {
  id: Id3;
  title: Title1;
  requirement: Requirement;
  required_evidence: RequiredEvidence;
}
export interface Run {
  id: Id4;
  project_id: ProjectId1;
  material_version_id: MaterialVersionId;
  rubric_id: RubricId;
  rubric_revision: RubricRevision;
  mode: Mode;
  status: Status;
  stage: Stage;
  provider?: Provider;
  model?: Model;
  prompt_version: PromptVersion;
  error?: Error;
}
export interface Document {
  id: Id5;
  material_version_id: MaterialVersionId1;
  logical_key: LogicalKey;
  filename: Filename;
  format: Format;
  sha256: Sha256;
  parse_status: ParseStatus;
}
export interface Block {
  id: Id6;
  document_id: DocumentId;
  ordinal: Ordinal;
  text: Text;
  locator: Locator;
}
export interface Locator {
  kind: Kind;
  index: Index;
  end_index?: EndIndex;
  block_index: BlockIndex;
}
export interface Claim {
  id: Id7;
  criterion_ids: CriterionIds;
  text: Text1;
  source: Span;
  comparison_key?: ComparisonKey;
}
export interface Span {
  block_id: BlockId;
  start: Start;
  end: End;
  quote: Quote;
}
export interface Evidence1 {
  id: Id8;
  criterion_id: CriterionId;
  claim_id?: ClaimId;
  source: Span;
  relation: Relation;
  citation_valid: CitationValid;
  validation_error?: ValidationError;
}
export interface Finding {
  id: Id9;
  fingerprint: Fingerprint;
  criterion_id: CriterionId1;
  kind: Kind1;
  severity: Severity;
  title: Title2;
  explanation: Explanation;
  claim_ids: ClaimIds;
  evidence_ids: EvidenceIds;
  searched_document_ids: SearchedDocumentIds;
}
export interface Repair {
  id: Id10;
  finding_id: FindingId;
  instruction: Instruction;
  status: Status1;
}
export interface CriterionAssessment {
  criterion_id: CriterionId2;
  status: Status2;
  evidence_ids: EvidenceIds1;
  finding_ids: FindingIds;
}
export interface Metrics {
  submission_readiness: SubmissionReadiness;
  rubric_coverage: RubricCoverage;
  verified_evidence: VerifiedEvidence;
  critical_risks: CriticalRisks;
  resolved_risks: ResolvedRisks;
}
export interface ReviewQuestion {
  id: Id11;
  finding_id: FindingId1;
  question: Question;
  why: Why;
  outline: Outline;
  evidence_ids: EvidenceIds2;
}
export interface VersionDiff {
  before_run_id: BeforeRunId;
  after_run_id: AfterRunId;
  comparable: Comparable;
  reason: Reason;
  entries: Entries;
}
export interface DiffEntry {
  fingerprint: Fingerprint1;
  status: Status3;
  before_finding_id: BeforeFindingId;
  after_finding_id: AfterFindingId;
}
export interface RunRequest {
  material_version_id: MaterialVersionId2;
  rubric_id: RubricId1;
  rubric_revision: RubricRevision1;
  mode: Mode1;
}
export interface MarkdownPreview {
  document_id: DocumentId1;
  filename: Filename1;
  size_bytes: SizeBytes;
  sha256: Sha2561;
  line_count: LineCount;
  blocks: Blocks1;
}
export interface SavedMaterial {
  id: Id12;
  filename: Filename2;
  size_bytes: SizeBytes1;
  sha256: Sha2562;
  line_count: LineCount1;
  created_at: CreatedAt;
  blocks: Blocks2;
}
export interface MaterialSummary {
  id: Id13;
  filename: Filename3;
  created_at: CreatedAt1;
  block_count: BlockCount;
}
export interface EvidenceAnnotation {
  id: Id14;
  material_id: MaterialId;
  block_id: BlockId1;
  source: Span;
  note?: Note;
  proposed_by?: ProposedBy;
  created_at: CreatedAt2;
}
export interface EvidenceAnnotationCreate {
  block_id: BlockId2;
  quote: Quote1;
  note?: Note1;
}
export interface RubricBinding {
  material_id: MaterialId1;
  rubric_id: RubricId2;
  rubric_revision: RubricRevision2;
  created_at: CreatedAt3;
}
export interface RubricBindingCreate {
  rubric_id: RubricId3;
  rubric_revision: RubricRevision3;
}
export interface CriterionEvidenceLink {
  id: Id15;
  material_id: MaterialId2;
  annotation_id: AnnotationId;
  rubric_id: RubricId4;
  rubric_revision: RubricRevision4;
  criterion_id: CriterionId3;
  rationale: Rationale;
  proposed_by?: ProposedBy1;
  created_at: CreatedAt4;
}
export interface CriterionEvidenceLinkCreate {
  annotation_id: AnnotationId1;
  criterion_id: CriterionId4;
  rationale: Rationale1;
}
export interface ProposalCandidate {
  id: Id16;
  proposal_id: ProposalId;
  ordinal: Ordinal1;
  block_id: BlockId3;
  quote: Quote2;
  rationale: Rationale2;
  risk_note?: RiskNote;
  validation_status: ValidationStatus;
  validation_code?: ValidationCode;
  review_status: ReviewStatus;
  reject_reason?: RejectReason;
  created_annotation_id?: CreatedAnnotationId;
  created_link_id?: CreatedLinkId;
  created_at: CreatedAt5;
}
export interface AgentProposal {
  id: Id17;
  material_id: MaterialId3;
  criterion_id: CriterionId5;
  rubric_id: RubricId5;
  rubric_revision: RubricRevision5;
  provider: Provider1;
  model: Model1;
  prompt_version: PromptVersion1;
  status: Status4;
  error?: Error1;
  created_at: CreatedAt6;
  candidates: Candidates;
}
export interface AgentProposalCreate {
  criterion_id: CriterionId6;
}
export interface ProposalCandidateReject {
  reason?: Reason1;
}
export interface ProposalAcceptance {
  annotation: EvidenceAnnotation;
  link: CriterionEvidenceLink;
}
export interface ApiError {
  code: Code;
  message: Message;
  details: Details;
}
